### ISSUE TITLE
System Error. Code: 5. Access is denied.

### ISSUE THREAD

**Issue by minhngwyen** [chris-wolcen/PoE-Tweaker#1] opened 2020-04-22 04:15 UTC
Hi, recently I have been getting this error from POE Tweaker. I have used POE Tweaker for quite a bit now and I had no issue with it until recently after I reinstalled windows.
[https://i.imgur.com/z2tQTW3.png](url)
Not sure what caused this. It seems like whatever caused this also make my trade macro to stop working, probably blocking it from parsing items from clipboard. 
I have tried to run POE with Drop Rights but I can't login. The game says "There's a patch you need to update to. Please restart Path of Exile". I have also tried to run all others programs with Admin rights ( POE Tweaker, Trade Macro) but that doesn't resolve the issue either.

**Comment by chris-wolcen** [comment] 2020-04-23 12:38
Delete PoET.ini from program directory. Does the message still appear?
If you get "There's a patch you need to update to. Please restart Path of Exile", then you're probably trying to run it with --nopatch parameter (but there's a pending patch on the server). Just remove --nopatch and you should be fine.

**Comment by minhngwyen** [comment] 2020-04-23 20:04
I tried deleting PoET.ini but the message still appear.
Also I am not running the game with --nopatch parameter. I only run it with -nologo, -softwareaudio, -disable-client-switching. I guess it's something that has to do with the game itself so I will reinstall it and see if anything changes.

**Comment by chris-wolcen** [comment] 2020-04-24 11:30
Does the program recreate PoET.ini after you get "System Error. Code: 5. Access is denied." error?
I reproduced the "Drop Rights" issue, I'm investigating it right now.

**Comment by chris-wolcen** [comment] 2020-04-24 16:51
_"There's a patch you need to update to. Please restart Path of Exile"_ error while in "Drop Rights" mode, turned out to be a bug in the program. Thank you very much for finding and reporting it! (It turns out that _lpCommandLine_ param of CreateProcess, **always** requires the first white space–delimited token to be the module name, not only if _lpApplicationName_ is NULL, in contrary to what MSDN says). This bug has been fixed in 1.07.

**Comment by minhngwyen** [comment] 2020-04-25 02:54
Hi, sorry for the late reply. I was a bit busy earlier.
Yes the program does create POET.ini. I just tried the 1.07 update and the Drop Rights feature works flawlessly now. It also fixes the problems I was having with my macros not working with POE. So I guess it's because POE has been ran with admin privileges. Even though I didn't remember ever ticking the "Run as Admin" box or anything similar. 
Nonetheless, everything is working now so it's all good. Thanks a lot for the quick update

**Closed as completed** 2020-04-25 11:01 UTC
Labels: bug
